name: Publish

on:
  push:
    branches: ["karsajobs-ui"]

jobs:
  build-and-push:
    name: Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: github-login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_SECRET }}
      - name: lint-dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: build-app-karsajobs-ui
        env:
          username: ${{ github.actor }}
        run: |
          docker build -t ghcr.io/$username/karsajobs-ui:latest .
          docker push ghcr.io/$username/karsajobs-ui:latest
      
